/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SharesRouteImport } from './routes/shares'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WriterApprovalsRouteImport } from './routes/writer.approvals'
import { Route as DocumentsNewRouteImport } from './routes/documents.new'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SharesRoute = SharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WriterApprovalsRoute = WriterApprovalsRouteImport.update({
  id: '/writer/approvals',
  path: '/writer/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsNewRoute = DocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shares': typeof SharesRoute
  '/terms': typeof TermsRoute
  '/documents/new': typeof DocumentsNewRoute
  '/writer/approvals': typeof WriterApprovalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shares': typeof SharesRoute
  '/terms': typeof TermsRoute
  '/documents/new': typeof DocumentsNewRoute
  '/writer/approvals': typeof WriterApprovalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/shares': typeof SharesRoute
  '/terms': typeof TermsRoute
  '/documents/new': typeof DocumentsNewRoute
  '/writer/approvals': typeof WriterApprovalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/inbox'
    | '/login'
    | '/privacy'
    | '/shares'
    | '/terms'
    | '/documents/new'
    | '/writer/approvals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/inbox'
    | '/login'
    | '/privacy'
    | '/shares'
    | '/terms'
    | '/documents/new'
    | '/writer/approvals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/documents'
    | '/inbox'
    | '/login'
    | '/privacy'
    | '/shares'
    | '/terms'
    | '/documents/new'
    | '/writer/approvals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SharesRoute: typeof SharesRoute
  TermsRoute: typeof TermsRoute
  WriterApprovalsRoute: typeof WriterApprovalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shares': {
      id: '/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof SharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writer/approvals': {
      id: '/writer/approvals'
      path: '/writer/approvals'
      fullPath: '/writer/approvals'
      preLoaderRoute: typeof WriterApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/new': {
      id: '/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof DocumentsNewRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsNewRoute: typeof DocumentsNewRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsNewRoute: DocumentsNewRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SharesRoute: SharesRoute,
  TermsRoute: TermsRoute,
  WriterApprovalsRoute: WriterApprovalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
